project:
  type: book

book:
  title: "Calculus"
  author: "Sam Mak"
  sidebar: 
    background: "black"
    search: false
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: darkly
    backgroundcolor: "black"
    date-modified: last-modified
    toc: false
    fontcolor: "#CCCCCC"
    css: mathematics.css
    number-sections: false
    section-divs: true
  
    grid: 
      body-width: 1100px
      margin-width: 100px
      sidebar-width: 180px
      
  pdf:
    documentclass: scrreprt
    

editor: source

