# Introduction


Words defined 
- Definition
- Theorem (theory being ignored)
- Axiom
- Statement 
- Proposition


**Definition**
- **Definition**
  - A definition is a statement that describes the essential/distinctive qualities/identity of the thing that's being defined with the purpose of it being understood and in turn studied and applied and/or have more complex things developed from it - **More**
  - A thing could be defined by one or more different parameters such as what it contains, its physical properties, behaviour when interacting with other things, purpose, usage 
  - The same thing (of the same meaning) could be defined differently, for example, the distinction of conceptual vs operational definition in science for different uses, the level of description for different intended level of understanding (e.g. a thing described in a general dictionary may differ from the same thing in a domain-specific dictionary - e.g. water in the general dictionary describes water as a transparent liquid while it is described as having a chemical configuration of H2O in a chemistry dictionary)
  
  
Latin structure 
- Inflection - Word modification
- There are several types of inflection
  - Declension - Inflections applied to nouns/adjectives
  - Conjugation - Inflections applied to verbs
  
**Statement (English)**
- An expression of the state of a particular thing/object 
- Derived from English "state"

**State (English)**
- The position(s)/place(s) of the property(properties) of a particular thing/object (i.e. the value(s)/options(s) taken by the property/properties of a particular thing/object among all its/their possibilities) 
- This includes any property(properties) of any particular thing(s)/object(s) within the particular general thing/object (when the primary thing/object has a complex/nested structure)
- Defined by Me
- Derived from Latin "status"

**The distinction between state and condition**
- While both are highly similar, I found some potential slight differences
- State relates to the thing/object of interest while condition relates to things/objects that are external but causally relevant to the thing/object of interest 
- Hence when "state" is used, it often has only one thing/object than when "condition" is used when it more often has multiple existentially distinct things/objects)
- But technically, condition stems from Latin condicio and condicere meaning agreement - It got generalised to a list of statements to be agreed/met/true for something to work

**Status (Latin)**
- **Semantics (OLD)**
  - Originally/primarily means (having been) standing/the fact of being in a standing position; alternatively means the position/place (where something is standing/set)
- **Grammatical Parent**
  - The perfect passive participle of sto or sisto
- **Linguistic/dialectic parent** 
  - Inherited from Proto-Italic "Statos", Proto-Indo-European "steh tus"

**Statos (sisto)**
- To stand, set, place

**Sto**
- To stand/to be in a standing position
- Inflections: stare, steti, statum

**Condition (English)**
- **Semantic**
  - A type of state, a state that needs/is required to be true/valid in order for a thing/object of primary interest to be true/valid
- **Linguistic/dialectic parent**
  - Derived from old French condicion (requisite/prerequisite/stipulation) which is derived from Latin condicio (agreement) which is derived from Latin condicere (agree upon)
  - Since about 1500s, it has its meaning generalised to state/situation and has included a sense of limitation/restriction (which is a sense derived from the original meaning)
  
  
**Theorem**
- A statement that is not self-evident hence needs to be proven for it to be taken as true 
- A speculation - A thought about a state that is not self-evident
- A state that is not self-evident 
- Derived from Latin theorema, which means a looking at - It is an abstraction of the action of looking at and making some judgement based on it

A summarised conclusion of a speculation/observation
The distinction between speculation vs observation
- Speculation - Examination, investigation 

Proposition = An expression of the state of a property of something 
- A statement that's being put forth 

A universal or general proposition or statement, not self-evident (thus distinguished from an axiom), but demonstrable by argument (in the strict sense, by necessary reasoning);


1612: Benvenuto's Passenger i. ii. 201 “Not corrupted by the fogs, nor vapours of lakes, stands, marrishes [It. laghi, stagni, e paludi], caues, durt, nor dust.”
1887: Daily News 29 June 2/7 “The London Grocery and Provision Exchange... There are already 140 *standholders.”

- Condition/situation/circumstance
- Not necessarily relative (e.g. position, rank)

1821: Shelley Epipsych. 320 “Each word would be The key of staunchless tears.”

Standing
1912: Eng. Hist. Rev. Oct. 652 “For a number of years after this Eustace was in good standing with the English king.”


The distinction between condition, situation and circumstance
- Condition is more related to physical properties 
- Situation is more about event 
- Condition is more specific, state is more general 

In mathematics, definitions tend to be how to make this thing work (to make upper concepts work)


We express ideas we want to be shared and may record it for it to be preserved 
- (in the form of words marked into some medium - e.g. sand, wood, bones, paper, stone)
- Physical movement (sets of movements, including facial expression)

Notes on language
- Language came in the form of sounds first, written language came in much later (maybe to allow ideas to be recorded)

Logical argument 

Pose
Posit
Position
Propose
Suppose 
Oppose 
Dispose 


Notion 
Idea 
Concept 
Thought

**Pose** - 
- 




$\Sigma \alpha \mu \upsilon \eta \lambda \text{  } \mu \alpha \kappa$

**Pono (Latin)**
- To place, set, put (in a specified position)
- Originated from Proto-Italic posno
- **Inflections**
  - **Ponere**
    - Place, set, put, situate
    - The present infinitive of Pono
  - **Posui**
    - First-person singular perfect active indicative of pono
  - **Positum**
    - An accusasive Supine of pono
  - **Positus**
    - Perfect passive participle of Pono


**Propono (Latin)**
- To place, set, put out/forward (for someone's attention/consideration to provoke some response - e.g. some judgement) (smak)
- To expose to view, exhibit [@old12]
- Composed of pro + pono
- **Inflections**
  - Proponere
  - Proposui
  - Propositum
  
**Proposition (English)**
- **Meaning**
  - Something that is being placed, set, put out/forward (for attention/consideration to provoke some response - e.g. some judgement) (smak)
- **Linguistic/dialectic parent**
  - Inherited from Latin propositio, which is the noun of proponere (an inflection of propono)
  

  
**Theorem (English)**
- **Meaning**
  - A proposition that is not self-evident/questionable hence requires some proof for credibility (i.e. for it to be taken as true) (smak)
  - A proposition that, in reality or in perception, does not always provoke a favourable/intended response to the individual/group who posited it, hence, is perceived to require some proof to provoke a favourable/intended response (favourable to/intended by the individual/group who posited it) (smak; expanded version to explain what "not self-evident" and "credible" means)
  - A universal or general proposition or statement, not self-evident (thus distinguished from an axiom), but demonstrable by argument (in the strict sense, by necessary reasoning [@oed89]
- **Linguistic/dialectic parent**
  - Derived from French théorème and late Latin and Greek theorema

**Theorema (Latin)**
- **Meaning**
  - A subject for investigation, a problem [@old12]
  - A proposition that is not self-evident/questionable hence requires some proof for credibility (i.e. for it to be taken as true) (smak)
- **Linguistic/diatectic parent**
  - Inherited from Greek theorema meaning speculation/proposition, which was in turn inherited from Greek theorein meaning 'look at', which in turn was inherited from Greek theoros meaning spectator
  - It is rather pointless to discuss about the semantic evolution, I will assume the significance of this word originated from mathematical theorems posited by Ancient Greek mathematicians, most prominently Pythagoras 
  
  
- smak, google/Oxford Languages, old/oed, Etymonline, Wikipedia/Wiktionary, Latin dictionary

**Theory**
- **Meaning**
- **Linguistic/dialectic parent**
  - Inherited from Late Latin theoria 
  
**Theoria (Late Latin)**
- **Meaning**
- **Linguistic/dialectic parent**
  - Inherited from Greek theoria 

  

**Finis (Latin)**
- **Meaning**
  - Anything that bounds/restricts/limits/reserves/constrains/confines some particular aspects/things of a thing of interest to some sets of possibilities (i.e. boundary/restrictions/limitations/reservations) among all possibilities of these aspects (smak)
  - A sense of 'ending' and 'finish' (English finish was inherited from the root of Latin finis - but they have slightly different meanings) - Hence, although this may seem similar to senses of division/separation/difference/distancing, they have different senses 
  - End (Google/Oxford Lanuguages)
  - The boundary of a territory or other area, or the line marking it [@old12, 772]
  - That which divides, a boundary, border... [Etymonline](https://www.etymonline.com/word/finish#etymonline_v_5960)
  
**Finio (Latin)**
- **Meaning**
  - To bound/restrict/limit/reserve/constrain/confine some particular aspects/things of a thing of interest to some sets of possibilities (i.e. boundary/restrictions/limitations/reservations) among all possibilities of these aspects (smak)
  - To mark out the boundaries of [@old12, p. 771]
  - To limit, set bounds; come to an end [Etymonline](https://www.etymonline.com/word/finite)
  - To limit, to end; to finish; to determine, to define; to mark out the boundaries [Online Latin Dictionary](https://www.online-latin-dictionary.com/latin-english-dictionary.php?parola=finio)
- **Inflections**
  - Finire - To bound between multiple particular things in a particular way
  - Finiui
  - Finii 
  - Finitum - The past participle of finio (can be used as an adjective) (i.e. finite in English)
- **Structure**
  - A composition of Latin finis and io 
  
  Limitation - Unable to go further a certain point 
  Restriction - Not allowed to go further a certain point 
  
**Finite (English)**
- **Meaning**
  - Having some boundaries/restrictions/limitations/reservations/constraints/confinements in some particular aspects/things of a thing of interest to some sets of possibilities among all possibilities of these aspects (smak)
  - Bounded/restricted/limited/reserved/constrained/confined
  - Fixed, determined [@oed89]
  - Having bounds, ends, or limits; bounded, limited [@oed89, 2nd def.]
- **Linguistic/dialectic parent**
  - Inherited from Latin finitus, which was inherited from Latin finitum, the past participle of Latin finire (head word is finio) (Google/Oxford Languages)


**Definio (Latin)**
- **Meaning**
  - Composed of de (the sense of "being from not being") + finio, hence, it means being finite from not being finite (smak)
  - To fix the limits of, delimit, bound, to mark out the limits of [@old12]
  
**Definitio (Latin)**
- **Meaning**
  - Anything that bounds/restricts/limits/reserves/constrains/confines some particular aspects/things of a thing of interest that's not being bounded to some sets of possibilities (i.e. boundary/restrictions/limitations/reservations) among all possibilities of these aspects (smak)
  - The fixing or marking of a boundary [@old12, p. 550]
  - A bounding, a boundary, a limiting, a prescribing, a definition, explanation [Online Etymology Dictionary](https://www.etymonline.com/word/definition#etymonline_v_25869)
  
**Definire**
- **Meaning**
  - Composed of de (the sense of "being from not being") + finio, hence, it means to make something that isn't finite to being finite 
  - To limit, determine, explain (Online Etymology Dictionary)
  - De means completely, finire means to bound, limit (inherited from finis which means boundary/end)
  
  
**Definite (English)**
- **Meaning**
  - Composed of de (meaning "from not being to being") + finite, hence, it means being finite from not being finite 
  - Having fixed or exact limits... [@oed89]
**Define (English)**
  - **Meaning**
    - To determine the boundary of; to settle the limits of [@oed89, 2nd def.]
    - To make definite [@oed89, 2nd def.]
  
**Definition (English)**
- **Meaning**
  - Anything that bounds/restricts/limits/reserves/constrains/confines some particular aspects/things of a thing of interest that's not being bounded to some sets of possibilities (i.e. boundary/restrictions/limitations/reservations) among all possibilities of these aspects (smak)
  - The setting of bounds or limits; limitation, restriction [@oed89]
- **Linguistic/dialectic parent**
  - Inherited from Latin definitio/definio, which is inherited from Latin definire (meaning set bounds to)
  

  

S3, S4, RC, R6

Word evoluation and post-modernism 
- Words are first fairly well defined, it will generate use cases (e.g. examples), some of which is well used, some not,because human learn associatively (learn by association), we understand the meaning of words by the many use cases we encounter, then we come up with a definition of the word based on all these use cases, so there is an error due to exposure and perception
  
  
**Axiom (English)**
- **Meaning**
  - A proposition that is considered/assumed unquestionable hence treated as fundamental/foundational to something else and is followed by an individual or a group (e.g. community) in relation to/within some scope of investigation/study/beliefs etc. - Some mathematicians conceptualise mathematical axioms as definitions (which are absolutely true in the mathematical space/world but necessarily true in the real/material/physical world) - This is the opposite of theorem (smak)
  - A proposition that commends itself to general acceptance; a well-estblished or universally-concided principle [@oed89]
- **Linguistic/dialectic parent**
  - Inherited from French axiome, which is inherited from Latin axioma, which is inherited from Greek axioma, which is inherited from Greek axioo, which is inherited from Greek axios (meaning worthy)

**Axioma (Latin)**
- **Meaning**
  - A fundamental proposition [@old12, p. 243]
  - A fundamental proposition/principle (Online Latin Dictionary)
  
**Axioma (Greek)**
- **Meaning**
  - What is thought to be/deemed worthy or fit, a requisite/requirement, a self-evident principle ([Wiktionary](https://en.wiktionary.org/wiki/axiom))

**Axioo (Greek)**
- **Meaning**
  - To think fit or worthy, to require, to demand ([Wiktionary](https://en.wiktionary.org/wiki/axiom))
  - Being in balance and hence having the same value/weight as, worthy, proper ([Wikipedia](https://en.wikipedia.org/wiki/Axiom#:~:text=8%20External%20links-,Etymology,worthy%22%2C%20%22proper%22.))
  
**Axios (Greek)**
- **Meaning**
  - Fit, worthy, weighting as much as, of value ([Wiktionary](https://en.wiktionary.org/wiki/axiom))
   
  
**Foundation (English)**
- **Meaning**
  - A thing on which other things are built/based/developed/relied (smak)
  - A thing that is considered to hold 
  - The word foundation implies there is something it is holding 
  - Foundations don't exist in themselves, but exist in relation to something 
- **Linguistic/dialectic parent**
  - Inherited from Old French foundation, which is inherited from Latin fundatio, which is inherited from Latin fundare
  - Fundamental and its synonym foundational originated from a common root of Latin fundare
  
**Fundamental**
- **Meaning**
  - A thing on which other things are built/based/developed/relied (smak)
- **Linguistic/dialectic parent**
  - Inherited from French fondamental, which is inherited from late Latin fundamentalis, which is inherited from Latin fundamentum, which is inherited from Latin fundare 
  - Fundamental and its synonym foundational originated from a common root of Latin fundare 

Positus - Position

**Definition in mathematics**
- **Introduction**
  - There are different types of definitions in mathematics (of mathematical objects)
- **Types of definitions**
  - Axiom
  - Conjecture
  - Corollary - A statement that follows on from another theorem
  - Lemma
  - Theorem
  
  
  - Definitions
  
**Conjecture 
  
  
```{r}
# Proposition
# Theorem 
# Theory
```
  
  